### PR TITLE
Wrote new log func to redirect build cmd's stdout/err streams to log …

### PR DESCRIPTION
**Pull request by sehqlr**
…file. Fixes race condition with logging goroutines

### CODE REVIEW

**Comment by langston-barrett** [comment]
I'm also experiencing this issue, I'll test this PR ASAP.

**Comment by langston-barrett** [comment]
My testing on this looks good.

**Comment by langston-barrett** [comment]
How does this compare to/interact with #22?

**Comment by sehqlr** [comment]
I'm going to close this PR, since it was likely obsoleted by #22.

**Pull request closed without merging**
